# DX@Scale CI/CD Template for GitHub
#----------------------------------------------------------------------------------------------------
# Maintained by @aly76 for DX@Scale
# Follows reference pipeline available at docs.dxatscale.io
# 
#-----------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit


# This pipeline is used to release a set of packages into respective environments

name: 'CD Pipeline - User Triggered'


on:
  workflow_dispatch:
    inputs:
      pathToReleaseDef:
        description: "Path to release definition file"
        required: true

jobs:
  ST:
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts
    environment:
      name: ST
    env:
      NPM_SCOPE: 'scope' #Change scope 
      #SET ONE OF THESE FOR METRICS
      #SFPOWERSCRIPTS_NEWRELIC: 'true'
      #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INGEST_KEY }}'
      #SFPOWERSCRIPTS_DATADOG: 'true'
      #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
      #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
   
      - name: Authenticate to ST sandbox
        run: |
          echo "${{ secrets.ST_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a st

      - name: Authenticate to NPM registry
        run: |
           echo "${{ env.NPM_SCOPE }}:registry=https://npm.pkg.github.com" > ~/.npmrc
           echo  "_authToken=${AUTH_TOKEN}" >> ~/.npmrc
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Release to environment
      - name: 'Release to ST'
        run: 'sfdx sfpowerscripts:orchestrator:release -u st -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ env.NPM_SCOPE }} --generatechangelog -b ${GITHUB_REF#refs/heads/}'


  Staging:
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts
      if: github.ref == 'refs/heads/main' || 'refs/heads/release/*'
    environment:
      name: STAGING
    needs: ST  
    env:
      NPM_SCOPE: 'scope' #Change scope 
      #SET ONE OF THESE FOR METRICS
      #SFPOWERSCRIPTS_NEWRELIC: 'true'
      #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INGEST_KEY }}'
      #SFPOWERSCRIPTS_DATADOG: 'true'
      #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
      #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

   
      - name: Authenticate to STAGING sandbox
        run: |
          echo "${{ secrets.STAGING_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a staging

      - name: Authenticate to NPM registry
        run: |
           echo "${{ env.NPM_SCOPE }}:registry=https://npm.pkg.github.com" > ~/.npmrc
           echo  "_authToken=${AUTH_TOKEN}" >> ~/.npmrc
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Release to environment
      - name: 'Release to STAGING'
         run: 'sfdx sfpowerscripts:orchestrator:release -u staging -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ env.NPM_SCOPE }} --generatechangelog -b ${GITHUB_REF#refs/heads/}'

  PROD:
    runs-on: ubuntu-latest
    container: dxatscale/sfpowerscripts
    if: contains(github.ref,'refs/heads/release')
    environment:
      name: PROD
    needs: SIT  
    env:
       NPM_SCOPE: 'scope' #Change scope 
      #SET ONE OF THESE FOR METRICS
      #SFPOWERSCRIPTS_NEWRELIC: 'true'
      #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INGEST_KEY }}'
      #SFPOWERSCRIPTS_DATADOG: 'true'
      #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
      #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Authenticate to PROD
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a prod

      - name: Authenticate to NPM registry
        run: |
           echo "${{ env.NPM_SCOPE }}:registry=https://npm.pkg.github.com" > ~/.npmrc
           echo  "_authToken=${AUTH_TOKEN}" >> ~/.npmrc
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Release to environment
      - name: 'Release to PROD'
    run: 'sfdx sfpowerscripts:orchestrator:release -u prod -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ env.NPM_SCOPE }} --generatechangelog -b ${GITHUB_REF#refs/heads/}'

