# DX@Scale CI/CD Template for GitHub
#----------------------------------------------------------------------------------------------------
# Maintained by @aly76 for DX@Scale
# Follows reference pipeline available at docs.dxatscale.io
# 
#-----------------------------------------------------------------------------------------------------
# To know more about dxatscale, visit https://docs.dxatscale.io
# To know more on sfpowerscripts, visit- https://sfpowerscripts.dxatscale.io/
# To know more on sfpowerkit, visit- https://github.com/Accenture/sfpowerkit


# This pipeline is used to release a set of packages into respective environments

name: 'CD Pipeline - User Triggered'


on:
  workflow_dispatch:
    inputs:
      pathToReleaseDef:
        description: "Path to release definition file"
        required: true

#Set the environment variables for tracking metrics
#env:
  #SFPOWERSCRIPTS_NEWRELIC: 'true'
  #SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INGEST_KEY }}'
  #SFPOWERSCRIPTS_DATADOG: 'true'
  #SFPOWERSCRIPTS_DATADOG_HOST: '${{ secrets.DATADOG_HOST }}'
  #SFPOWERSCRIPTS_DATADOG_API_KEY: '${{ secrets.DATADOG_API_KEY }}'

jobs:
  ST:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts-rc:develop
    environment:
      name: ST
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
   
      - name: Authenticate to ST sandbox
        run: |
          echo "${{ secrets.ST_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a st

      - uses: actions/setup-node@v3
        with:
         registry-url: 'https://npm.pkg.github.com'

      # Release to environment
      - name: 'Release to ST'
        run: 'sfdx sfpowerscripts:orchestrator:release -u st -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname ${GITHUB_REF#refs/heads/} -g "::group::,::endgroup::" '
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  SIT:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts-rc:develop
    if: github.ref == 'refs/heads/main' || 'refs/heads/release/*'
    environment:
      name: SIT
    needs: ST  

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

   
      - name: Authenticate to SIT sandbox
        run: |
          echo "${{ secrets.SIT_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a sit

      - uses: actions/setup-node@v3
        with:
         registry-url: 'https://npm.pkg.github.com'

      # Release to environment
      - name: 'Release to SIT'
        run: 'sfdx sfpowerscripts:orchestrator:release -u sit -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname ${GITHUB_REF#refs/heads/} -g "::group::,::endgroup::" '
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  PROD:
    runs-on: ubuntu-latest
    container: ghcr.io/dxatscale/sfpowerscripts-rc:develop
    if: contains(github.ref,'refs/heads/release')
    environment:
      name: PROD
    needs: SIT  

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Authenticate to PROD
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f ./authfile -a prod

      - name: Authenticate to NPM registry
        run: |
           echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" > ~/.npmrc
           echo  "_authToken=${AUTH_TOKEN}" >> ~/.npmrc
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Release to environment
      - name: 'Release to PROD'
        run: 'sfdx sfpowerscripts:orchestrator:release -u prod -p ${{ github.event.inputs.pathToReleaseDef }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname ${GITHUB_REF#refs/heads/} -g "::group::,::endgroup::" '
